parser:
  babel-eslint

env:
  browser: true
  es2021: true

extends:
  - 'plugin:react/recommended'
  - airbnb
  - 'prettier/react'
  - prettier

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - prettier
  - react-hooks

rules:
  "import/order": ["error", { "newlines-between": "always", "groups": ["builtin", "external", "internal", "parent", "sibling", "index"] }]
  max-len: ["error", { code: 120 }]
  "prettier/prettier": [ 2 , {
      "singleQuote": true,
      "trailingComma": "all",
      "printWidth": 120,
  }]
