require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/**/*
    - docs/**/*
    - tmp
    - node_modules/**/*
    - app/javascript/**/*

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

# Rails/Date:
#   Description: >-
#                   Checks the correct usage of date aware methods,
#                   such as Date.today, Date.current etc.
#   Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Max: 50

Metrics/ClassLength:
  Max: 150

# Lint/EmptyWhen:
#   Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/LineLength:
  Max: 150
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true

# Rails/NotNullColumn:
#   Enabled: false

# Style/Lambda:
#   Enabled: false
