mailer:
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>

rails:
  secret_key_base: <%= ENV['RAILS_SECRET_KEY_BASE'] %>
  max_threads: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  min_threads: <%= ENV['RAILS_MIN_THREADS'] || 5 %>
  port: <%= ENV['PORT'] || 3000 %>
  env: <%= ENV['RAILS_ENV'] || 'development' %>
  pidfile: <%= ENV['PIDFILE'] || 'tmp/pids/server.pid' %>
  eager_load: <%= ENV['EAGER_LOAD'] || false %>

database:
  name: <%= ENV['DB_NAME']%>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

rollbar:
  env: <%= ENV['ROLLBAR_ENV'] || 'development'%>
  client_access_token: <%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN']%>
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN']%>
